- name: Remove download directory ~/{{ env_type }}
  file:
    path: '~/{{ env_type }}'
    state: absent

- name: Create download directory ~/{{ env_type }}
  file:
    path: '~/{{ env_type }}'
    state: directory

- name: Fetch files that requires authentication
  get_url:
    url: '{{ base_nexus_repo_url }}/{{ item[0] }}/{{ item[1] }}'
    dest: '~/{{ env_type }}/{{ item[1] }}'
    url_username: '{{ nexus_username }}'
    url_password: '{{ nexus_password }}'
  loop: '{{ artifacts }}'
  loop_control:
    label: '{{ item[1] }}'

- name: Restart JBoss
  include_tasks: library/restart-jboss.yaml

- name: Copy files from rollback dir {{ rollback_dir }}
  include_tasks: library/copy-war-files.yaml
  vars:
    source_dir: '~/{{ env_type }}'
    dest_dir: '{{ deployment_dir }}'
  loop: "{{ artifacts }}"
  loop_control:
    label: '{{ item[1] }}'
